apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: flask-${CICD_GIT_BRANCH}-Development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-${CICD_GIT_BRANCH}-Development
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-${CICD_GIT_BRANCH}-Development
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: flask-${CICD_GIT_BRANCH}-Development
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "2"
        ports:
        - containerPort: 8080
   
