stages:
  - name: test
    steps:
    - runScriptConfig:
        image: python:3.8.0
        shellScript: |-
          pip install pycodestyle
          apt install git -y
          git clone http://10.50.0.20/root/devops-flask.git
          #pwd
          #ls -al
          pycodestyle sample/flask/dockerfile/*.py
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./sample/flask/dockerfile/Dockerfile
        buildContext: .
        tag: demoyuw/devops-flask:${CICD_EXECUTION_SEQUENCE}
  - name: deploy flask deployment
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-deployment.yaml
  - name: deploy flask service
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-service.yaml
