stages:
  - name: build sonarqube runner image
    steps:
    - publishImageConfig:
        dockerfilePath: ./build/sonarqube/sonar-runner/Dockerfile
        buildContext: .
        tag: demoyuw/devops-sonarrunner:${CICD_EXECUTION_SEQUENCE}
#  - name: run sonarqube runner
#    steps:
#    - applyYamlConfig:
#        path: ./build/sonarqube/sonar-runner/flask-deployment.yaml
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./sample/flask/dockerfile/Dockerfile
        buildContext: .
        tag: demoyuw/devops-flask:${CICD_EXECUTION_SEQUENCE}
  - name: deploy dev flask-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/Development/flask-deployment.yaml
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/Development/flask-service.yaml
    when:
      branch:
        exclude: [ master ]
  - name: deploy staging flask-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/Staging/flask-deployment.yaml
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/Staging/flask-service.yaml
    when:
      branch:
        exclude: [ master ]
  - name: deploy production flask-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/Production/flask-deployment.yaml
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/Production/flask-service.yaml
    when:
      branch: master
      event: [ push ]