stages:
  - name: test
    steps:
    - runScriptConfig:
        image: python:3.8.0
        shellScript: |-
          pip install pycodestyle
          pycodestyle sample/flask/dockerfile/
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./sample/flask/dockerfile/Dockerfile
        buildContext: .
        tag: demoyuw/devops-flask:${CICD_EXECUTION_SEQUENCE}
  - name: deploy flask-${CICD_GIT_BRANCH} deployment and service
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-deployment.yaml
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-service.yaml
