stages:
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./sample/flask/dockerfile/Dockerfile
        buildContext: .
        tag: demoyuw/devops-flask:${CICD_EXECUTION_SEQUENCE}
        # tag: demoyuw/devops-flask
  - name: deploy flask deployment
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-deployment.yaml
  - name: deploy flask service
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-service.yaml
