stages:
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./sample/flask/dockerfile/Dockerfile
        buildContext: .
        tag: demoyuw/devops-flask:${CICD_EXECUTION_SEQUENCE}
  - name: test
    steps:
    - runScriptConfig:
        image: demoyuw/devops-flask
        shellScript: |-
          pip install pycodestyle
          pycodestyle --count -qq ./sample/flask/dockerfile
  - name: deploy flask deployment
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-deployment.yaml
  - name: deploy flask service
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-service.yaml
