stages:
  - name: Flatten secrets to files
    steps:
    - runScriptConfig:
        image: 10.20.0.71:5443/dockerhub/library/alpine
        shellScript: echo $k8s_config > k8s_config; echo $environments_json > environments.json;
      envFrom:
      - sourceName: devops-api
        sourceKey: environments_json
        targetKey: environments_json
      - sourceName: devops-api
        sourceKey: k8s_config
        targetKey: k8s_config
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
        pushRemote: true
        registry: 10.20.0.71:5443
      env:
        PLUGIN_INSECURE: "true"
        PLUGIN_MTU: "1000"
  - name: deploy ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./k8s-yaml/flask-deployment.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/flask-service.yaml

  - name: Checkmarx test
    steps:
      - runScriptConfig:
          image: 10.20.0.71:5443/dockerhub/iiiorg/checkmarx-runner
          shellScript: ln -s "$(pwd)" /usr/src/app/repo; cd /usr/src/app; ls; node app.js;
        env:
          git_url: ${CICD_GIT_URL}
          git_branch: ${CICD_GIT_BRANCH}
          git_commit_id: ${CICD_GIT_COMMIT}
          verbose: true
        envFrom:
          - sourceName: nexus
            sourceKey: api-origin
            targetKey: api_origin
          - sourceName: nexus
            sourceKey: username
            targetKey: api_username
          - sourceName: nexus
            sourceKey: password
            targetKey: api_password
          - sourceName: checkmarx
            sourceKey: username
            targetKey: username
          - sourceName: checkmarx
            sourceKey: password
            targetKey: password
          - sourceName: checkmarx
            sourceKey: client-secret
            targetKey: client_secret
          - sourceName: checkmarx
            sourceKey: cm-url
            targetKey: cm_url

  - name: Run webinspect-runner
    steps:
      - runScriptConfig:
          image: 10.20.0.71:5443/dockerhub/iiiorg/webinspect-runner
          shellScript: cd /usr/src/app; node /usr/src/app/app.js
        env:
          inspect_url: http://10.20.0.72:32400/
          project_name: ${CICD_GIT_REPO_NAME}
          git_branch: ${CICD_GIT_BRANCH}
          git_commit_id: ${CICD_GIT_COMMIT}
          verbose: true
        envFrom:
          - sourceName: webinspect
            sourceKey: wi-base-url
            targetKey: wi_base_url
          - sourceName: nexus
            sourceKey: username
            targetKey: api_username
          - sourceName: nexus
            sourceKey: password
            targetKey: api_password
          - sourceName: nexus
            sourceKey: api-origin
            targetKey: api_origin