stages:
#  - name: build sonarqube runner image
#    steps:
#    - publishImageConfig:
#        dockerfilePath: ./build/sonarqube/sonar-runner/Dockerfile
#        buildContext: .
#        tag: devops-sonarrunner:${CICD_EXECUTION_SEQUENCE}
#    - applyYamlConfig:
#        path: ./build/sonarqube/sonar-runner/k8s-yaml/sonar-runner-deployment.yaml
  - name: Publish flask image
    steps:
    - publishImageConfig:
        dockerfilePath: ./sample/flask/dockerfile/Dockerfile
        buildContext: .
        tag: demoyuw/devops-flask:${CICD_EXECUTION_SEQUENCE}
  - name: deploy flask-${CICD_GIT_BRANCH} environment
    steps:
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-deployment.yaml
    - applyYamlConfig:
        path: ./sample/flask/k8s-yaml/flask-service.yaml
