"""merge

Revision ID: 02265f92da74
Revises: e54eca5d79fa
Create Date: 2020-12-02 16:22:07.474391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02265f92da74'
down_revision = 'e54eca5d79fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
