"""added kubernetes_sa_name columns to user_plugin_relation table

Revision ID: e54eca5d79fa
Revises: f26e1beadd1f
Create Date: 2020-11-26 09:27:18.872954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54eca5d79fa'
down_revision = 'f26e1beadd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plugin_relation', sa.Column('kubernetes_sa_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plugin_relation', 'kubernetes_sa_name')
    # ### end Alembic commands ###
