"""Make foreign keys cascade

Revision ID: e6ea1b5539b9
Revises: 
Create Date: 2020-11-20 10:25:35.142087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ea1b5539b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checkmarx_repo_id_fkey', 'checkmarx', type_='foreignkey')
    op.create_foreign_key(None, 'checkmarx', 'project_plugin_relation', ['repo_id'], ['git_repository_id'], ondelete='CASCADE')
    op.drop_constraint('flows_requirement_id_fkey', 'flows', type_='foreignkey')
    op.drop_constraint('flows_project_id_fkey', 'flows', type_='foreignkey')
    op.create_foreign_key(None, 'flows', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flows', 'requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('parameters_project_id_fkey', 'parameters', type_='foreignkey')
    op.create_foreign_key(None, 'parameters', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pipeline_software_config_project_id_fkey', 'pipeline_software_config', type_='foreignkey')
    op.drop_constraint('pipeline_software_config_software_id_fkey', 'pipeline_software_config', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_software_config', 'pipeline_software', ['software_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_software_config', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_plugin_relation_project_id_fkey', 'project_plugin_relation', type_='foreignkey')
    op.create_foreign_key(None, 'project_plugin_relation', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_user_role_project_id_fkey', 'project_user_role', type_='foreignkey')
    op.drop_constraint('project_user_role_user_id_fkey', 'project_user_role', type_='foreignkey')
    op.create_foreign_key(None, 'project_user_role', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_user_role', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('requirements_project_id_fkey', 'requirements', type_='foreignkey')
    op.create_foreign_key(None, 'requirements', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_cases_project_id_fkey', 'test_cases', type_='foreignkey')
    op.create_foreign_key(None, 'test_cases', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_items_test_case_id_fkey', 'test_items', type_='foreignkey')
    op.drop_constraint('test_items_project_id_fkey', 'test_items', type_='foreignkey')
    op.create_foreign_key(None, 'test_items', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'test_items', 'test_cases', ['test_case_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_results_project_id_fkey', 'test_results', type_='foreignkey')
    op.create_foreign_key(None, 'test_results', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('test_values_test_case_id_fkey', 'test_values', type_='foreignkey')
    op.drop_constraint('test_values_test_item_id_fkey', 'test_values', type_='foreignkey')
    op.drop_constraint('test_values_project_id_fkey', 'test_values', type_='foreignkey')
    op.create_foreign_key(None, 'test_values', 'test_items', ['test_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'test_values', 'test_cases', ['test_case_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'test_values', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_plugin_relation_user_id_fkey', 'user_plugin_relation', type_='foreignkey')
    op.create_foreign_key(None, 'user_plugin_relation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_plugin_relation', type_='foreignkey')
    op.create_foreign_key('user_plugin_relation_user_id_fkey', 'user_plugin_relation', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'test_values', type_='foreignkey')
    op.drop_constraint(None, 'test_values', type_='foreignkey')
    op.drop_constraint(None, 'test_values', type_='foreignkey')
    op.create_foreign_key('test_values_project_id_fkey', 'test_values', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('test_values_test_item_id_fkey', 'test_values', 'test_items', ['test_item_id'], ['id'])
    op.create_foreign_key('test_values_test_case_id_fkey', 'test_values', 'test_cases', ['test_case_id'], ['id'])
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.create_foreign_key('test_results_project_id_fkey', 'test_results', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'test_items', type_='foreignkey')
    op.drop_constraint(None, 'test_items', type_='foreignkey')
    op.create_foreign_key('test_items_project_id_fkey', 'test_items', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('test_items_test_case_id_fkey', 'test_items', 'test_cases', ['test_case_id'], ['id'])
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.create_foreign_key('test_cases_project_id_fkey', 'test_cases', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'requirements', type_='foreignkey')
    op.create_foreign_key('requirements_project_id_fkey', 'requirements', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_user_role', type_='foreignkey')
    op.drop_constraint(None, 'project_user_role', type_='foreignkey')
    op.create_foreign_key('project_user_role_user_id_fkey', 'project_user_role', 'user', ['user_id'], ['id'])
    op.create_foreign_key('project_user_role_project_id_fkey', 'project_user_role', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_plugin_relation', type_='foreignkey')
    op.create_foreign_key('project_plugin_relation_project_id_fkey', 'project_plugin_relation', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'pipeline_software_config', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_software_config', type_='foreignkey')
    op.create_foreign_key('pipeline_software_config_software_id_fkey', 'pipeline_software_config', 'pipeline_software', ['software_id'], ['id'])
    op.create_foreign_key('pipeline_software_config_project_id_fkey', 'pipeline_software_config', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'parameters', type_='foreignkey')
    op.create_foreign_key('parameters_project_id_fkey', 'parameters', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'flows', type_='foreignkey')
    op.drop_constraint(None, 'flows', type_='foreignkey')
    op.create_foreign_key('flows_project_id_fkey', 'flows', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('flows_requirement_id_fkey', 'flows', 'requirements', ['requirement_id'], ['id'])
    op.drop_constraint(None, 'checkmarx', type_='foreignkey')
    op.create_foreign_key('checkmarx_repo_id_fkey', 'checkmarx', 'project_plugin_relation', ['repo_id'], ['git_repository_id'])
    # ### end Alembic commands ###
