"""Add harbor info

Revision ID: f26e1beadd1f
Revises: c28f89773c50
Create Date: 2020-11-25 14:34:20.656898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26e1beadd1f'
down_revision = 'c28f89773c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_plugin_relation', sa.Column('harbor_project_id', sa.Integer(), nullable=True))
    op.add_column('user_plugin_relation', sa.Column('harbor_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plugin_relation', 'harbor_user_id')
    op.drop_column('project_plugin_relation', 'harbor_project_id')
    # ### end Alembic commands ###
