apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checkmark-scan
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "30 17 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request GET 'http://devopsapi-service:10009/checkmarx/cronjob_scan'
          restartPolicy: OnFailure
