apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-pipeline-version
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request POST 'http://devopsapi-service:10009/pipeline/check_update'
          restartPolicy: OnFailure
