apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-cronjob
spec:
  concurrencyPolicy: Forbid
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:7.76.1
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - curl -i -X PATCH http://devops-api:10009/deploy/applications/cronjob
          restartPolicy: OnFailure
