apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deploy-cronjob
spec:
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:7.76.1
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - curl -i -X PATCH http://devopsapi-service:10009/deploy/applications/cronjob
          restartPolicy: OnFailure
