apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-count-commits
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request GET 'http://devops-api:10009/sync_gitlab/count_each_pj_commits_by_days'
          restartPolicy: OnFailure
