apiVersion: batch/v1
kind: CronJob
metadata:
  name: harbor-auto-del-image
spec:
  startingDeadlineSeconds: 180
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "0 16 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request DELETE 'http://devopsapi-service:10009/v2/harbor/image/auto/del'
          restartPolicy: OnFailure
