apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-remove-extra-executions
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "0 16 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request POST 'http://devops-api:10009/monitoring/k8s/remove_extra_executions'
          restartPolicy: OnFailure
