apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8s-alert-unusual-pods
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request POST 'http://devopsapi-service:10009/monitoring/k8s/pod_alert'
          restartPolicy: OnFailure
