apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8s-count-pods-restart-times
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request POST 'http://devopsapi-service:10009/monitoring/k8s/collect_pod_restart_times_by_hour'
          restartPolicy: OnFailure
