apiVersion: batch/v1
kind: CronJob
metadata:
  name: remove-k8s-pods-data
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "0 16 1 * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request DELETE 'http://devops-api:10009/monitoring/k8s/collect_pod_restart_times_by_hour'
          restartPolicy: OnFailure
