apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: remove-sbom-file
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request PATCH 'http://devopsapi-service:10009/v2/sbom/remove'
          restartPolicy: OnFailure