apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: report-data
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "0 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request GET 'http://devopsapi-service:10009/system_info_report'
          restartPolicy: OnFailure
