apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-data
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "30 1 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request PUT 'http://devopsapi-service:10009/system_info_report'
          restartPolicy: OnFailure
