apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: routine-job-by-day
spec:
  concurrencyPolicy: Forbid
  schedule: "0 21 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:7.76.1
              imagePullPolicy: IfNotPresent
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cornjob-bot
                      key: cornjob-token
              command: ["/bin/sh"]
              args: ["-c", "curl --location --request POST 'http://devopsapi-service:10009/routine_job/by_day' --header \"Authorization: Bearer $TOKEN\""]
          restartPolicy: OnFailure
