apiVersion: batch/v1
kind: CronJob
metadata:
  name: routine-job-by-month
spec:
  concurrencyPolicy: Forbid
  schedule: "30 4 1 * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: curl
              image: curlimages/curl:7.76.1
              imagePullPolicy: IfNotPresent
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cornjob-bot
                      key: cornjob-token
              command: ["/bin/sh"]
              args: ["-c", "curl --location --request POST 'http://devops-api:10009/routine_job/by_month' --header \"Authorization: Bearer $TOKEN\""]
          restartPolicy: OnFailure