apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-redmine
spec:
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            env: 
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cornjob-bot
                    key: cornjob-token
            command: ["/bin/sh"]
            args: ["-c", "curl -H \"Authorization: Bearer $TOKEN\" --location --request GET 'http://devopsapi-service:10009/sync_redmine'"]
          restartPolicy: OnFailure