apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-template
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.76.1
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl --location --request GET 'http://devopsapi-service:10009/template_list_for_cronjob?force_update=1'
          restartPolicy: OnFailure
