"""add webinspect

Revision ID: 00b0402a8197
Revises: 9b20106c9cc2
Create Date: 2020-12-15 15:06:44.687728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b0402a8197'
down_revision = '9b20106c9cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uk_projects_name', 'projects', ['name'])
    op.create_table('web_inspect',
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_id', sa.String(), nullable=True),
    sa.Column('stats', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(('project_name',), ['projects.name'], ondelete='CASCADE',
                            name='fk_web_inspect_project_name'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_table('web_inspect')
    # ### end Alembic commands ###
