"""Add starred project

Revision ID: 01a378b3cae9
Revises: 78a808f09713
Create Date: 2021-07-01 15:28:32.474946

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision = '01a378b3cae9'
down_revision = '78a808f09713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starred_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starred_project')
    # ### end Alembic commands ###
