"""create application table

Revision ID: 029012e6bd65
Revises: 8cf4e1b2f67d
Create Date: 2021-08-13 15:34:43.621324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029012e6bd65'
down_revision = '8cf4e1b2f67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('registry_id', sa.Integer(), nullable=True),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('yaml', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
