"""add cluster column for cluster info

Revision ID: 036075783010
Revises: 48b83276a09a
Create Date: 2021-08-19 14:16:12.638832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036075783010'
down_revision = '48b83276a09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('cluster_host', sa.String(), nullable=True))
    op.add_column('cluster', sa.Column('cluster_name', sa.String(), nullable=True))
    op.add_column('cluster', sa.Column('cluster_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'cluster_user')
    op.drop_column('cluster', 'cluster_name')
    op.drop_column('cluster', 'cluster_host')
    # ### end Alembic commands ###
