"""remove repo_id ForeignKey and and repo_name

Revision ID: 03e29af71de0
Revises: c7d1617876ef
Create Date: 2021-04-13 18:53:51.126026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e29af71de0'
down_revision = 'c7d1617876ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_commit_number_each_days', sa.Column('repo_name', sa.String(), nullable=True))
    op.drop_constraint('git_commit_number_each_days_repo_id_fkey', 'git_commit_number_each_days', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('git_commit_number_each_days_repo_id_fkey', 'git_commit_number_each_days', 'project_plugin_relation', ['repo_id'], ['git_repository_id'], ondelete='CASCADE')
    op.drop_column('git_commit_number_each_days', 'repo_name')
    # ### end Alembic commands ###
