"""remove_deadline_column

Revision ID: 055c98811e57
Revises: 8070283b6ddf
Create Date: 2022-01-29 14:27:28.711752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '055c98811e57'
down_revision = '8070283b6ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_message', 'due_datetime')
    op.drop_column('notification_message', 'no_deadline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_message', sa.Column('no_deadline', sa.BOOLEAN(), autoincrement=False))
    op.add_column('notification_message', sa.Column('due_datetime',
                  postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
