"""modify_cmas_column

Revision ID: 071e6082e75b
Revises: b203dfb0c839
Create Date: 2021-12-17 11:44:59.794821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071e6082e75b'
down_revision = 'b203dfb0c839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CMAS', sa.Column('filenames', sa.JSON(), nullable=True))
    op.drop_column('CMAS', 'filename')
    op.drop_column('CMAS', 'cm_project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CMAS', sa.Column('cm_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('CMAS', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('CMAS', 'filenames')
    # ### end Alembic commands ###
