"""'add_from_project_name_col'

Revision ID: 076599cf8d72
Revises: 7ab5b3d298a9
Create Date: 2022-05-16 13:24:29.843505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076599cf8d72'
down_revision = '7ab5b3d298a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_project', sa.Column('from_project_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_project', 'from_project_name')
    # ### end Alembic commands ###
