"""IssueGitLabRelation_commit_id_type_error

Revision ID: 0a1183cfef0e
Revises: 741675916f6f
Create Date: 2021-12-13 15:51:57.055475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1183cfef0e'
down_revision = '741675916f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_git_lab_relation', sa.Column('commit_id', sa.String(), nullable=False))
    op.drop_column('issue_git_lab_relation', 'id')
    op.drop_constraint('project_commit_endpoint_commit_id_key', 'project_commit_endpoint', type_='unique')
    op.drop_column('project_commit_endpoint', 'commit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_commit_endpoint', sa.Column('commit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('project_commit_endpoint_commit_id_key', 'project_commit_endpoint', ['commit_id'])
    op.add_column('issue_git_lab_relation', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('issue_git_lab_relation', 'commit_id')
    # ### end Alembic commands ###
