"""'add_title_in_notif'

Revision ID: 0abb6dd4b854
Revises: f32d3c521de0
Create Date: 2022-04-07 13:41:07.589373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abb6dd4b854'
down_revision = 'f32d3c521de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_message', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_message', 'title')
    # ### end Alembic commands ###
