"""add_table_lock

Revision ID: 0abf7b51469f
Revises: cae154d4dcb4
Create Date: 2021-09-27 19:34:14.920363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abf7b51469f'
down_revision = 'cae154d4dcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_lock', sa.Boolean(), nullable=True),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lock')
    # ### end Alembic commands ###
