"""add_table_custom_issue_filter

Revision ID: 122d240db263
Revises: 1f3e2747c7b2
Create Date: 2021-11-02 11:12:14.987169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122d240db263'
down_revision = '1f3e2747c7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_issue_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('custom_filter', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_issue_filter')
    # ### end Alembic commands ###
