"""update redmine table

Revision ID: 12ec7b485164
Revises: ad4f6277a1e6
Create Date: 2021-04-12 14:28:46.301875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ec7b485164'
down_revision = 'ad4f6277a1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_rank', sa.Column('project_count', sa.Integer(), nullable=True))
    op.drop_column('issue_rank', 'prject_count')
    op.add_column('project_member', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('project_member', 'user_id')
    sa.PrimaryKeyConstraint('id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_member', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('project_member', 'id')
    op.add_column('issue_rank', sa.Column('prject_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('issue_rank', 'project_count')
    # ### end Alembic commands ###
