"""add_column_collect_at_in_server_data_collection

Revision ID: 14c91ed94a89
Revises: 448be6485c04
Create Date: 2021-10-05 09:50:14.011917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c91ed94a89'
down_revision = '448be6485c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_data_collection', sa.Column('collect_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_data_collection', 'collect_at')
    # ### end Alembic commands ###
