"""remove_id_from_message_reply

Revision ID: 172e6aaeecaf
Revises: 982d27c06e3d
Create Date: 2022-02-08 16:02:34.253104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172e6aaeecaf'
down_revision = '982d27c06e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_message_reply_slip', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notification_message_reply_slip', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notification_message_reply_slip', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_message_reply_slip', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('notification_message_reply_slip', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notification_message_reply_slip', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
