"""add_next_tag_id_in_Tag

Revision ID: 1902122bdbcd
Revises: ce38e27a59d3
Create Date: 2023-04-24 11:07:31.806854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1902122bdbcd'
down_revision = 'ce38e27a59d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('next_tag_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tag_next_tag_id'), 'tag', ['next_tag_id'], unique=False)
    op.create_foreign_key('tag_next_tag_id_fkey', 'tag', 'tag', ['next_tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_next_tag_id_fkey', 'tag', type_='foreignkey')
    op.drop_index(op.f('ix_tag_next_tag_id'), table_name='tag')
    op.drop_column('tag', 'next_tag_id')
    # ### end Alembic commands ###
