"""add col group_name in TemplateListCache

Revision ID: 1a61c68e40ee
Revises: 23f04a227b1a
Create Date: 2021-05-12 17:09:28.455961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a61c68e40ee'
down_revision = '23f04a227b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_list_cache', sa.Column('group_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_list_cache', 'group_name')
    # ### end Alembic commands ###
