"""add_table_alert_comming_record

Revision ID: 1b8a04b1970b
Revises: 76c3a044b4ae
Create Date: 2021-08-27 03:46:26.557307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8a04b1970b'
down_revision = '76c3a044b4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_comming_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('before_update_time', sa.DateTime(), nullable=True),
    sa.Column('after_update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_comming_record')
    # ### end Alembic commands ###
