"""add_table_ProjectParentSonRelation_remove_WBSCache

Revision ID: 1f0e2963b684
Revises: cffe0a76c763
Create Date: 2022-01-06 14:13:14.663359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f0e2963b684'
down_revision = 'cffe0a76c763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_parent_son_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('son_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['son_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wbs_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wbs_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_field', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='wbs_cache_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wbs_cache_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wbs_cache_pkey')
    )
    op.drop_table('project_parent_son_relation')
    # ### end Alembic commands ###
