"""add_total_commit

Revision ID: 1f3e2747c7b2
Revises: 923af8e3156c
Create Date: 2021-10-20 10:35:52.814673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3e2747c7b2'
down_revision = '923af8e3156c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_commit_number_each_days', sa.Column('total_commit_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('git_commit_number_each_days', 'total_commit_number')
    # ### end Alembic commands ###
