"""update sync_redmine related tables

Revision ID: 23f04a227b1a
Revises: 856b68aedb0b
Create Date: 2021-05-10 09:54:36.602047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f04a227b1a'
down_revision = '856b68aedb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redmine_issue', sa.Column('assigned_to_login', sa.String(), nullable=True))
    op.add_column('redmine_project', sa.Column('pm_user_login', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redmine_project', 'pm_user_login')
    op.drop_column('redmine_issue', 'assigned_to_login')
    # ### end Alembic commands ###
