"""adjust zap

Revision ID: 252ce5626f65
Revises: dd864194a0a5
Create Date: 2021-04-06 15:09:44.634453

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '252ce5626f65'
down_revision = 'dd864194a0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zap', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zap', 'finished_at')
    # ### end Alembic commands ###
