"""Create Tag and IssueTag Table

Revision ID: 297fdad4825b
Revises: e0ebcd77f922
Create Date: 2021-09-09 16:14:13.388555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297fdad4825b'
down_revision = 'e0ebcd77f922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_tag',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
