"""add_user_fromad_column

Revision ID: 2d76784ebc41
Revises: 532d1f271b18
Create Date: 2021-04-22 18:44:20.879760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d76784ebc41'
down_revision = '532d1f271b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('from_ad', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'from_ad')
    # ### end Alembic commands ###
