"""'remove_harbor_pj_id_col'

Revision ID: 2f019b0e85b5
Revises: a25a2a0bb803
Create Date: 2022-05-23 15:01:48.903311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f019b0e85b5'
down_revision = 'a25a2a0bb803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harbor_scan', 'harbor_project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harbor_scan', sa.Column('harbor_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
