"""project_table_create_base_example_col

Revision ID: 32f13f742b1a
Revises: f5d0699db128
Create Date: 2022-03-09 15:30:55.046332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f13f742b1a'
down_revision = 'f5d0699db128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('base_example', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'base_example')
    # ### end Alembic commands ###
