"""Add Cluster Table Column createor_id, create_at, update_at

Revision ID: 3432e808027e
Revises: 8fdd0e8d0c2d
Create Date: 2021-08-03 16:21:31.264469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3432e808027e'
down_revision = '8fdd0e8d0c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('cluster', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('cluster', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'cluster', 'user', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cluster', type_='foreignkey')
    op.drop_column('cluster', 'update_at')
    op.drop_column('cluster', 'creator_id')
    op.drop_column('cluster', 'create_at')
    # ### end Alembic commands ###
