"""rebuild_IssueCommitRelation

Revision ID: 34b0f0d7cd47
Revises: 9fb4be14b5bc
Create Date: 2021-12-14 08:54:43.466338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34b0f0d7cd47'
down_revision = '9fb4be14b5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_commit_relation',
    sa.Column('commit_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.Column('commit_time', sa.DateTime(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('web_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commit_id')
    )
    op.drop_table('issue_git_lab_relation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_git_lab_relation',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('web_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('commit_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('commit_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='issue_git_lab_relation_project_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('issue_commit_relation')
    # ### end Alembic commands ###
