"""add user column ad_update_at

Revision ID: 3848c2a26348
Revises: 4d2e7a69ca2e
Create Date: 2021-04-26 17:38:19.075147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3848c2a26348'
down_revision = '4d2e7a69ca2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('title', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
