"""drop old redmine project

Revision ID: 3d55942c29d0
Revises: 626d063566c3
Create Date: 2021-04-14 11:26:11.943921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d55942c29d0'
down_revision = '626d063566c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redmine_project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redmine_project',
    sa.Column('project_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_issue_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complete_percent', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expired_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('member_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pm_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pm_user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_issue_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unclosed_issue_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('project_id', name='redmine_project_pkey')
    )
    # ### end Alembic commands ###
