"""add_table_user_notify_type

Revision ID: 3db576758a28
Revises: f640cdf79826
Create Date: 2022-06-16 13:57:48.247083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db576758a28'
down_revision = 'f640cdf79826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notify_type',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification', sa.Boolean(), nullable=True),
    sa.Column('mail', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notify_type')
    # ### end Alembic commands ###
