"""add_table_alert_message

Revision ID: 448be6485c04
Revises: ea13d68ca55f
Create Date: 2021-10-04 11:12:55.347205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448be6485c04'
down_revision = 'ea13d68ca55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('alert_code', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_message')
    # ### end Alembic commands ###
