"""add project owner

Revision ID: 467fc59e6a76
Revises: 252ce5626f65
Create Date: 2021-04-09 11:03:30.072623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '467fc59e6a76'
down_revision = '252ce5626f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'owner')
    # ### end Alembic commands ###
