"""add project owner

Revision ID: 467fc59e6a76
Revises: 252ce5626f65
Create Date: 2021-04-09 11:03:30.072623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '467fc59e6a76'
down_revision = '252ce5626f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('red_members')
    op.drop_table('red_issues')
    op.drop_table('red_projects')
    op.add_column('projects', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'owner')
    op.create_table('red_projects',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('project_id', name='red_projects_tmp_pkey1')
    )
    op.create_table('red_issues',
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('issue_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('assignee', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('issue_id', name='red_issues_tmp_pkey')
    )
    op.create_table('red_members',
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('member_id', name='red_members_tmp_pkey')
    )
    # ### end Alembic commands ###
