"""add_column_changeNo_changeUrl_in_IssueExtension

Revision ID: 478d461fe750
Revises: 6c4d5bb37851
Create Date: 2022-07-22 08:56:06.512336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478d461fe750'
down_revision = '6c4d5bb37851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_extensions', sa.Column('ITSMS_no', sa.String(), nullable=True))
    op.add_column('issue_extensions', sa.Column('ITSMS_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_extensions', 'ITSMS_url')
    op.drop_column('issue_extensions', 'ITSMS_no')
    # ### end Alembic commands ###
