"""modify_trace_order

Revision ID: 48b83276a09a
Revises: d13d20a64fcd
Create Date: 2021-08-17 16:39:43.508338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b83276a09a'
down_revision = 'd13d20a64fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trace_order', 'project_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('trace_order_project_id_fkey', 'trace_order', type_='foreignkey')
    op.create_foreign_key('trace_order_project_id_fkey', 'trace_order', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trace_order_project_id_fkey', 'trace_order', type_='foreignkey')
    op.create_foreign_key('trace_order_project_id_fkey', 'trace_order', 'projects', ['project_id'], ['id'])
    op.alter_column('trace_order', 'project_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
