"""add_template_repository_name

Revision ID: 4aa317ad8650
Revises: 076599cf8d72
Create Date: 2022-05-18 11:18:47.303281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa317ad8650'
down_revision = '076599cf8d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_project', sa.Column('template_repository_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_project', 'template_repository_name')
    # ### end Alembic commands ###
