"""'rm_ui_route_json'

Revision ID: 4c0789b4ad92
Revises: b22da4c8f705
Create Date: 2022-07-27 10:15:15.524790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c0789b4ad92'
down_revision = 'b22da4c8f705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ui_route_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_route_json',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ui_route', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='ui_route_json_pkey')
    )
    # ### end Alembic commands ###
