"""set user from_ad column defalut false

Revision ID: 4d2e7a69ca2e
Revises: 65e32ff674e1
Create Date: 2021-04-26 11:07:25.003385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2e7a69ca2e'
down_revision = '65e32ff674e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
