"""'add_fully_commit_col'

Revision ID: 4f7be24431e1
Revises: dcdab710bed3
Create Date: 2022-05-26 17:30:27.587468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7be24431e1'
down_revision = 'dcdab710bed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harbor_scan', sa.Column('fully_commit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harbor_scan', 'fully_commit')
    # ### end Alembic commands ###
