"""add_log_in_CheckMarx

Revision ID: 5045d9a6076f
Revises: 76085b6973e3
Create Date: 2022-08-05 14:19:45.595857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5045d9a6076f'
down_revision = '76085b6973e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkmarx', sa.Column('logs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkmarx', 'logs')
    # ### end Alembic commands ###
