"""add_action_type_ADD_TAG_

Revision ID: 54dc194b8646
Revises: 61ee47c4c796
Create Date: 2021-11-22 16:07:55.179628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dc194b8646'
down_revision = '61ee47c4c796'
branch_labels = None
depends_on = None


def upgrade():
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE actiontype ADD VALUE 'ADD_TAG'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
