"""add_rancher_pipline_number_each_days

Revision ID: 561e2829f8d0
Revises: 3432e808027e
Create Date: 2021-08-10 04:01:43.318255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561e2829f8d0'
down_revision = '3432e808027e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rancher_pipline_number_each_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pipline_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rancher_pipline_number_each_days')
    # ### end Alembic commands ###
