"""add webinspect

Revision ID: 59031209de47
Revises: 9b20106c9cc2
Create Date: 2020-12-15 14:07:03.956104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59031209de47'
down_revision = '9b20106c9cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_inspect',
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_id', sa.String(), nullable=True),
    sa.Column('stats', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('scan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_inspect')
    # ### end Alembic commands ###
