"""add_column_active_in_system_parameter

Revision ID: 5b3b0201deca
Revises: 96a7e3a61347
Create Date: 2021-10-08 11:48:45.279141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3b0201deca'
down_revision = '96a7e3a61347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_parameter', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_parameter', 'active')
    # ### end Alembic commands ###
