"""add_column_logs_in_TestResults

Revision ID: 5c4bc0b05957
Revises: fd4a15862536
Create Date: 2022-03-16 13:59:24.218503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4bc0b05957'
down_revision = 'fd4a15862536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('logs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'logs')
    # ### end Alembic commands ###
