"""remove_unuse_table

Revision ID: 61ee47c4c796
Revises: 122d240db263
Create Date: 2021-11-22 09:10:06.656998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61ee47c4c796'
down_revision = '122d240db263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_tag_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_tag_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('historys', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='issue_tag_history_pkey')
    )
    # ### end Alembic commands ###
