"""GitCommitNumberEachDays table add created_at column

Revision ID: 626d063566c3
Revises: 03e29af71de0
Create Date: 2021-04-14 10:13:08.884480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626d063566c3'
down_revision = '03e29af71de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_commit_number_each_days', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('git_commit_number_each_days', 'created_at')
    # ### end Alembic commands ###
