"""add user title column

Revision ID: 63cac0772a9c
Revises: 3848c2a26348
Create Date: 2021-04-27 11:32:08.841872

"""

# revision identifiers, used by Alembic.
revision = '63cac0772a9c'
down_revision = '65e32ff674e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
