"""add user title column

Revision ID: 63cac0772a9c
Revises: 3848c2a26348
Create Date: 2021-04-27 11:32:08.841872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cac0772a9c'
down_revision = '3848c2a26348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('title', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title')
    # ### end Alembic commands ###
