"""add department title column for ad

Revision ID: 65e32ff674e1
Revises: 2d76784ebc41
Create Date: 2021-04-26 10:33:52.902126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e32ff674e1'
down_revision = '2d76784ebc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('title', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title')
    op.drop_column('user', 'department')
    # ### end Alembic commands ###
