"""add pipeline course

Revision ID: 6a1bd1326e46
Revises: 1902122bdbcd
Create Date: 2023-06-06 18:36:21.015436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1bd1326e46'
down_revision = '1902122bdbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source_code_num', sa.Integer(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_course')
    # ### end Alembic commands ###
