"""add application table status_id and release_id column

Revision ID: 6b19109165fd
Revises: 029012e6bd65
Create Date: 2021-08-13 17:32:05.636330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b19109165fd'
down_revision = '029012e6bd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('release_id', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('status_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'status_id')
    op.drop_column('application', 'release_id')
    # ### end Alembic commands ###
