"""add_action_type_enable_and_disable_plugin

Revision ID: 6c4d5bb37851
Revises: 918fc253f98a
Create Date: 2022-07-21 13:53:40.010389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4d5bb37851'
down_revision = '918fc253f98a'
branch_labels = None
depends_on = None


def upgrade():
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'ENABLE_PLUGIN'")
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'DISABLE_PLUGIN'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
