"""change_IssueGitLabRelation_commit_id_type

Revision ID: 741675916f6f
Revises: 76f9e203cb5b
Create Date: 2021-12-13 23:15:32.910180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741675916f6f'
down_revision = '76f9e203cb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_git_lab_relation', sa.Column('id', sa.String(), nullable=False))
    op.drop_column('issue_git_lab_relation', 'commit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_git_lab_relation', sa.Column('commit_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('issue_git_lab_relation', 'id')
    # ### end Alembic commands ###
