"""create_table_PipelineUpdateVersion

Revision ID: 76085b6973e3
Revises: 8f4654be2a9a
Create Date: 2022-08-01 12:11:42.653066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76085b6973e3'
down_revision = '8f4654be2a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_update_version',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_update_version')
    # ### end Alembic commands ###
