"""Add Project Id

Revision ID: 78a808f09713
Revises: e55508cb2d34
Create Date: 2021-06-30 09:13:43.767122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a808f09713'
down_revision = 'e55508cb2d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'release', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'release', type_='foreignkey')
    op.drop_column('release', 'project_id')
    # ### end Alembic commands ###
