"""Remove pluginsoftware redundant column

Revision ID: 7ca18f645262
Revises: 01a378b3cae9
Create Date: 2021-07-05 17:54:57.698967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca18f645262'
down_revision = '01a378b3cae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin_software', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_software', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
