"""add_alert_service_id_in_NotificationMessage

Revision ID: 7cab3638ebbf
Revises: 90864a70343e
Create Date: 2022-04-29 17:25:42.535211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cab3638ebbf'
down_revision = '90864a70343e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_message', sa.Column('alert_service_id', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_message', 'alert_service_id')
    # ### end Alembic commands ###
