"""add disabled column at Registries Table

Revision ID: 7dc516bd42ef
Revises: 83e7e83f406b
Create Date: 2021-08-24 10:54:13.470510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc516bd42ef'
down_revision = '83e7e83f406b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registries', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registries', 'disabled')
    # ### end Alembic commands ###
