"""add_col_key_cloak_user_id_in_UserPluginRelation

Revision ID: 7e7ef6a8fc29
Revises: d22f27fbeaad
Create Date: 2023-02-04 16:15:47.497576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7ef6a8fc29'
down_revision = 'd22f27fbeaad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_plugin_relation', sa.Column('key_cloak_group_id', sa.String(), nullable=True))
    op.add_column('user_plugin_relation', sa.Column('key_cloak_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plugin_relation', 'key_cloak_user_id')
    op.drop_column('project_plugin_relation', 'key_cloak_group_id')
    # ### end Alembic commands ###
