"""add_log_in_CMAS

Revision ID: 8070283b6ddf
Revises: c665b55318b7
Create Date: 2022-01-24 14:55:52.670586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8070283b6ddf'
down_revision = 'c665b55318b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CMAS', sa.Column('logs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CMAS', 'logs')
    # ### end Alembic commands ###
