"""add_column_a_ert_CMAS

Revision ID: 859423a22639
Revises: d1cc07fffdd3
Create Date: 2021-12-02 20:08:57.946086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859423a22639'
down_revision = 'd1cc07fffdd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CMAS', sa.Column('a_ert', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CMAS', 'a_ert')
    # ### end Alembic commands ###
