"""recreate source_code_len

Revision ID: 8f4654be2a9a
Revises: 4c0789b4ad92
Create Date: 2022-07-28 11:23:56.942134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f4654be2a9a'
down_revision = '4c0789b4ad92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gitlab_source_code_lens',
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('commit_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_code_num', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('branch', 'project_id')
    )
    op.drop_table('gitlab_source_code_len')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gitlab_source_code_len',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commit_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_code_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='gitlab_source_code_len_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='gitlab_source_code_len_pkey')
    )
    op.drop_table('gitlab_source_code_lens')
    # ### end Alembic commands ###
