"""add_activity_enum_ENABLE_ISSUE_CHECK

Revision ID: 90864a70343e
Revises: f06c4c5159ec
Create Date: 2022-04-15 08:45:16.710586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90864a70343e'
down_revision = 'f06c4c5159ec'
branch_labels = None
depends_on = None


def upgrade():
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'ENABLE_ISSUE_CHECK'")
        op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'DISABLE_ISSUE_CHECK'")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
