"""change_column_name_in_alert_message

Revision ID: 923af8e3156c
Revises: 5b3b0201deca
Create Date: 2021-10-15 16:31:36.019439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923af8e3156c'
down_revision = '5b3b0201deca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_message', sa.Column('code', sa.Integer(), nullable=True))
    op.drop_column('alert_message', 'alert_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_message', sa.Column('alert_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('alert_message', 'code')
    # ### end Alembic commands ###
