"""add sonarqube

Revision ID: 94db0a2748c7
Revises: d5b7b6b0adbe
Create Date: 2021-03-15 11:54:15.002729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94db0a2748c7'
down_revision = 'd5b7b6b0adbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sonarqube',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('measures', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_name'], ['projects.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sonar_qube')
    # ### end Alembic commands ###
