"""add IssueTag Table

Revision ID: 95ed84e07ad5
Revises: d9e85cc2ff3b
Create Date: 2021-09-09 23:56:51.065470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ed84e07ad5'
down_revision = 'd9e85cc2ff3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_tag_issue_id'), 'issue_tag', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_tag_issue_id'), table_name='issue_tag')
    op.drop_table('issue_tag')
    # ### end Alembic commands ###
