"""Add deployment uuid

Revision ID: 97b3f3995a94
Revises: 7ca18f645262
Create Date: 2021-07-09 15:55:30.454586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b3f3995a94'
down_revision = '7ca18f645262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nexus_version', sa.Column('deployment_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nexus_version', 'deployment_uuid')
    # ### end Alembic commands ###
