"""'add_alert_level_col'

Revision ID: 982d27c06e3d
Revises: 055c98811e57
Create Date: 2022-02-08 11:32:17.572703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982d27c06e3d'
down_revision = '055c98811e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_message', sa.Column('alert_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_message', 'alert_level')
    # ### end Alembic commands ###
