"""add plugin_software_type_id column

Revision ID: 987ed3077e84
Revises: 7707fc9fbdde
Create Date: 2021-06-07 10:58:09.196144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987ed3077e84'
down_revision = '7707fc9fbdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_software', sa.Column('type_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin_software', 'type_id')
    # ### end Alembic commands ###
