"""Add checkmarx stats

Revision ID: 9b20106c9cc2
Revises: 0fb7e7cc03a0
Create Date: 2020-12-07 16:29:29.196850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b20106c9cc2'
down_revision = '0fb7e7cc03a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkmarx', sa.Column('stats', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkmarx', 'stats')
    # ### end Alembic commands ###
