"""remove id from template_list_cache table

Revision ID: 9c79db35e936
Revises: b016f57b5445
Create Date: 2021-04-12 07:42:48.237256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c79db35e936'
down_revision = 'b016f57b5445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_list_cache', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_list_cache', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
