"""add_table_alert_unchange_record

Revision ID: 9e79c81782e5
Revises: 1b8a04b1970b
Create Date: 2021-08-27 05:44:38.153789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e79c81782e5'
down_revision = '1b8a04b1970b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_unchange_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('before_update_time', sa.DateTime(), nullable=True),
    sa.Column('after_update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('alert_comming_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_comming_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('before_update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('after_update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='alert_comming_record_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='alert_comming_record_pkey')
    )
    op.drop_table('alert_unchange_record')
    # ### end Alembic commands ###
