"""'add_message_parameter'

Revision ID: 9e8a0854f547
Revises: 4f7be24431e1
Create Date: 2022-05-30 14:52:48.088183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8a0854f547'
down_revision = '4f7be24431e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_message', sa.Column('message_parameter', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_message', 'message_parameter')
    # ### end Alembic commands ###
