"""add new redmine project

Revision ID: 9f14298dd293
Revises: 3d55942c29d0
Create Date: 2021-04-14 11:26:48.891730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f14298dd293'
down_revision = '3d55942c29d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redmine_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('pm_user_id', sa.Integer(), nullable=True),
    sa.Column('pm_user_name', sa.String(), nullable=True),
    sa.Column('complete_percent', sa.Float(), nullable=True),
    sa.Column('closed_issue_count', sa.Integer(), nullable=True),
    sa.Column('unclosed_issue_count', sa.Integer(), nullable=True),
    sa.Column('total_issue_count', sa.Integer(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('expired_day', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redmine_project')
    # ### end Alembic commands ###
