"""modify_issus_git_lab_relation

Revision ID: 9fb4be14b5bc
Revises: 0a1183cfef0e
Create Date: 2021-12-14 08:35:37.453696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb4be14b5bc'
down_revision = '0a1183cfef0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_git_lab_relation', sa.Column('commit_message', sa.String(), nullable=True))
    op.add_column('issue_git_lab_relation', sa.Column('commit_time', sa.DateTime(), nullable=True))
    op.add_column('project_commit_endpoint', sa.Column('commit_id', sa.String(), nullable=True))
    op.create_unique_constraint("project_commit_endpoint_commit_id_key", 'project_commit_endpoint', ['commit_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_commit_endpoint_commit_id_key", 'project_commit_endpoint', type_='unique')
    op.drop_column('project_commit_endpoint', 'commit_id')
    op.drop_column('issue_git_lab_relation', 'commit_time')
    op.drop_column('issue_git_lab_relation', 'commit_message')
    # ### end Alembic commands ###
