"""create_example_tag_in_project_table

Revision ID: a15480f4a42f
Revises: 3cdd3c688615
Create Date: 2022-03-15 09:29:25.047483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15480f4a42f'
down_revision = '3cdd3c688615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('example_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'example_tag')
    # ### end Alembic commands ###
