"""add_default_in_trace_order

Revision ID: a1dd6024c785
Revises: 036075783010
Create Date: 2021-08-20 11:58:47.315405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1dd6024c785'
down_revision = '036075783010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trace_order', sa.Column('default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trace_order', 'default')
    # ### end Alembic commands ###
