"""add project creator column

Revision ID: a42969a0d096
Revises: ec4c3aab9b73
Create Date: 2021-05-04 16:50:25.223646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42969a0d096'
down_revision = 'ec4c3aab9b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
