"""add_column_is_inheritance_member_in_Project

Revision ID: aeb42c11f16d
Revises: 9e8a0854f547
Create Date: 2022-05-31 12:14:09.746878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb42c11f16d'
down_revision = '9e8a0854f547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_inheritance_member', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_inheritance_member')
    # ### end Alembic commands ###
