"""add autoincrement tag

Revision ID: b016f57b5445
Revises: fe09c879214d
Create Date: 2021-04-12 07:29:08.325414

"""

# revision identifiers, used by Alembic.
revision = 'b016f57b5445'
down_revision = 'fe09c879214d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
