"""add_default_alert_days

Revision ID: b0fe26c527b3
Revises: 6b19109165fd
Create Date: 2021-08-16 10:42:09.224678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fe26c527b3'
down_revision = '6b19109165fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_alert_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unchange_days', sa.Integer(), nullable=True),
    sa.Column('comming_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('default_alert_days')
    # ### end Alembic commands ###
