"""change_column_type_in_Issuecommitrelation

Revision ID: b203dfb0c839
Revises: c523323c62c7
Create Date: 2021-12-15 16:09:04.240322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b203dfb0c839'
down_revision = 'c523323c62c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_commit_relation', sa.Column('issue_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('issue_commit_relation', 'issue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_commit_relation', sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('issue_commit_relation', 'issue_ids')
    # ### end Alembic commands ###
