"""alert redmine_projects columns

Revision ID: b2195255b274
Revises: e58bc89ce410
Create Date: 2021-05-25 14:37:57.874303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2195255b274'
down_revision = 'e58bc89ce410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redmine_project', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('redmine_project', sa.Column('owner_login', sa.String(), nullable=True))
    op.add_column('redmine_project', sa.Column('owner_name', sa.String(), nullable=True))
    op.drop_column('redmine_project', 'pm_user_login')
    op.drop_column('redmine_project', 'pm_user_name')
    op.drop_column('redmine_project', 'pm_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redmine_project', sa.Column('pm_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('redmine_project', sa.Column('pm_user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('redmine_project', sa.Column('pm_user_login', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('redmine_project', 'owner_name')
    op.drop_column('redmine_project', 'owner_login')
    op.drop_column('redmine_project', 'owner_id')
    # ### end Alembic commands ###
