"""add create and update date in plugin software

Revision ID: b363e9236a88
Revises: db23d561f2b4
Create Date: 2021-04-17 17:47:10.367963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b363e9236a88'
down_revision = 'db23d561f2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_software', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('plugin_software', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin_software', 'update_at')
    op.drop_column('plugin_software', 'create_at')
    # ### end Alembic commands ###
