"""update sync redmine table

Revision ID: b68635229cc9
Revises: 9f14298dd293
Create Date: 2021-04-15 15:56:45.388650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68635229cc9'
down_revision = '9f14298dd293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redmine_issue', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('redmine_issue', sa.Column('status', sa.String(), nullable=True))
    op.add_column('redmine_issue', sa.Column('sync_date', sa.DateTime(), nullable=True))
    op.alter_column('redmine_issue', 'project_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='status_id::integer',
               existing_nullable=True)
    op.alter_column('redmine_issue', 'status_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='status_id::integer',
               existing_nullable=True)
    op.add_column('redmine_project', sa.Column('project_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redmine_project', 'project_status')
    op.alter_column('redmine_issue', 'status_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               postgresql_using='status_id::varchar',
               existing_nullable=True)
    op.alter_column('redmine_issue', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               postgresql_using='status_id::varchar',
               existing_nullable=True)
    op.drop_column('redmine_issue', 'sync_date')
    op.drop_column('redmine_issue', 'status')
    op.drop_column('redmine_issue', 'start_date')
    # ### end Alembic commands ###
