"""add_table_release_repo_tag

Revision ID: b7d3a4a8f308
Revises: d1669069c4a1
Create Date: 2022-05-10 20:31:11.578552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7d3a4a8f308'
down_revision = 'd1669069c4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_repo_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('custom_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('release', 'custom_paths')
    op.drop_column('release', 'tags')
    op.drop_column('release', 'extra_image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('extra_image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('release', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('release', sa.Column('custom_paths', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_table('release_repo_tag')
    # ### end Alembic commands ###
