"""create_is_lock_col

Revision ID: b96d6e6491cb
Revises: 9b28682a8925
Create Date: 2022-02-22 14:31:54.036641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96d6e6491cb'
down_revision = '9b28682a8925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_lock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_lock')
    # ### end Alembic commands ###
