"""add disabled column for Registries

Revision ID: bca34d393dd5
Revises: a1dd6024c785
Create Date: 2021-08-23 08:53:50.098464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca34d393dd5'
down_revision = 'a1dd6024c785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registries', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registries', 'disabled')
    # ### end Alembic commands ###
