"""'add_nf_recipient_tab'

Revision ID: bf01087eb736
Revises: c0869fb4e93a
Create Date: 2022-03-24 16:35:06.551477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf01087eb736'
down_revision = 'c0869fb4e93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_message_recipient',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_parameter', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['notification_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'type_id')
    )
    op.drop_column('notification_message', 'type_id')
    op.drop_column('notification_message', 'type_parameter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_message', sa.Column('type_parameter', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('notification_message', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('notification_message_recipient')
    # ### end Alembic commands ###
