"""create_last_login_for_user_table

Revision ID: c0869fb4e93a
Revises: 5c4bc0b05957
Create Date: 2022-03-21 15:17:18.521496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0869fb4e93a'
down_revision = '5c4bc0b05957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
