"""Delete origin db version

Revision ID: c28f89773c50
Revises: e6ea1b5539b9
Create Date: 2020-11-20 11:35:08.478610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28f89773c50'
down_revision = 'e6ea1b5539b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_version',
    sa.Column('version', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('version', name='db_version_pkey')
    )
    # ### end Alembic commands ###
