"""Add test generated issue table

Revision ID: c296a8ba63ac
Revises: 987ed3077e84
Create Date: 2021-06-21 16:19:59.125357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c296a8ba63ac'
down_revision = '987ed3077e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_generated_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('software_name', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_id', sa.String(), nullable=True),
    sa.Column('result_table', sa.String(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registries', sa.Column('registires_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('registries', 'registries_id')
    op.drop_table('test_generated_issue')
    # ### end Alembic commands ###
