"""modify_trace_order

Revision ID: c4dba050e379
Revises: d13d20a64fcd
Create Date: 2021-08-17 14:19:40.708508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dba050e379'
down_revision = 'd13d20a64fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
