"""add_create_at_in_projectparentsonrelation

Revision ID: c665b55318b7
Revises: daaf84c340cd
Create Date: 2022-01-20 11:23:27.870904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c665b55318b7'
down_revision = 'daaf84c340cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_parent_son_relation', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_parent_son_relation', 'created_at')
    # ### end Alembic commands ###
