"""change to owner_id

Revision ID: c706d9781fe8
Revises: 67b6620e3940
Create Date: 2021-04-09 14:58:48.734812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c706d9781fe8'
down_revision = '67b6620e3940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('projects_owner_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['owner_id'], ['id'])
    op.drop_column('projects', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_owner_fkey', 'projects', 'user', ['owner'], ['id'])
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###
