"""create GitCommitNumberEachDays table

Revision ID: c7d1617876ef
Revises: fc2e4916a772
Create Date: 2021-04-13 16:32:30.854867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d1617876ef'
down_revision = 'fc2e4916a772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_commit_number_each_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('commit_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['project_plugin_relation.git_repository_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git_commit_number_each_days')
    # ### end Alembic commands ###
