"""create_ui_route_json_tab

Revision ID: c8cf0f79f185
Revises: e4354fd3c12d
Create Date: 2022-03-15 11:12:00.040800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cf0f79f185'
down_revision = 'e4354fd3c12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_route_json',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ui_route', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ui_route_json')
    # ### end Alembic commands ###
