"""change SystemParameter key to name

Revision ID: cae154d4dcb4
Revises: 17e220f9fafb
Create Date: 2021-09-24 13:42:12.722846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae154d4dcb4'
down_revision = '17e220f9fafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_parameter', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('system_parameter', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_parameter', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('system_parameter', 'name')
    # ### end Alembic commands ###
