"""add restart number for deploy application

Revision ID: d10a9ad9f863
Revises: 90a8f40d4f2c
Create Date: 2021-09-06 10:33:18.670376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10a9ad9f863'
down_revision = '90a8f40d4f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('restart_number', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('restarted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'restarted_at')
    op.drop_column('application', 'restart_number')
    # ### end Alembic commands ###
