"""add_column_extra_image_path_in_Release

Revision ID: d1669069c4a1
Revises: e25e528d33c0
Create Date: 2022-05-09 11:18:55.197440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1669069c4a1'
down_revision = 'e25e528d33c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('extra_image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'extra_image_path')
    # ### end Alembic commands ###
