"""add_column_size_in_cmas

Revision ID: d1cc07fffdd3
Revises: c0ea091d1315
Create Date: 2021-12-02 16:44:16.209155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cc07fffdd3'
down_revision = 'c0ea091d1315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CMAS', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CMAS', 'size')
    # ### end Alembic commands ###
