"""add application table harbor and k8s info column

Revision ID: d32f26370f21
Revises: 4ecd1fce7b33
Create Date: 2021-08-16 16:38:28.079509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd32f26370f21'
down_revision = '4ecd1fce7b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('harbor_info', sa.String(), nullable=True))
    op.add_column('application', sa.Column('k8s_yaml', sa.String(), nullable=True))
    op.add_column('application', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('application', 'yaml')
    op.drop_column('application', 'update_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('application', sa.Column('yaml', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('application', 'updated_at')
    op.drop_column('application', 'k8s_yaml')
    op.drop_column('application', 'harbor_info')
    # ### end Alembic commands ###
