"""add_column_status_finish_at_on_webinspect

Revision ID: d3e9ebe9efa7
Revises: f4e18cc12da5
Create Date: 2023-03-28 16:24:06.844045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e9ebe9efa7'
down_revision = 'f4e18cc12da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_inspect', sa.Column('status', sa.String(), nullable=True))
    op.add_column('web_inspect', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_inspect', 'finished_at')
    op.drop_column('web_inspect', 'status')
    # ### end Alembic commands ###
