"""add PipelineLogsCache table

Revision ID: d5b7b6b0adbe
Revises: fa67fc942daf
Create Date: 2020-12-29 16:03:33.994588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b7b6b0adbe'
down_revision = 'fa67fc942daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_logs_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('ci_pipeline_id', sa.String(), nullable=True),
    sa.Column('run', sa.Integer(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_logs_cache')
    # ### end Alembic commands ###
