"""remove IssueTag

Revision ID: d9e85cc2ff3b
Revises: 297fdad4825b
Create Date: 2021-09-09 23:45:14.471343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e85cc2ff3b'
down_revision = '297fdad4825b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_tag',
    sa.Column('issue_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='issue_tag_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', name='issue_tag_pkey')
    )
    # ### end Alembic commands ###
