"""remove unused table

Revision ID: db23d561f2b4
Revises: b6f80f2c2d8e
Create Date: 2021-04-16 11:58:15.582640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db23d561f2b4'
down_revision = 'b6f80f2c2d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_software_config')
    op.drop_table('pipeline_software')
    op.drop_table('pipeline_phase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_phase',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_phase_Id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pipeline_phase_pkey')
    )
    op.create_table('pipeline_software',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pipeline_software_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pipeline_software_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pipeline_software_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('software_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sample', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='pipeline_software_config_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_id'], ['pipeline_software.id'], name='pipeline_software_config_software_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pipeline_software_config_pkey')
    )
    # ### end Alembic commands ###
