"""'add_scan_overview'

Revision ID: dcdab710bed3
Revises: 2f019b0e85b5
Create Date: 2022-05-25 17:06:31.412531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdab710bed3'
down_revision = '2f019b0e85b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harbor_scan', sa.Column('scan_overview', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('harbor_scan', 'scan_overview')
    # ### end Alembic commands ###
