"""add zap

Revision ID: dd864194a0a5
Revises: 94db0a2748c7
Create Date: 2021-04-01 10:10:59.651527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd864194a0a5'
down_revision = '94db0a2748c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('full_log', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_name'], ['projects.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zap')
    # ### end Alembic commands ###
