"""add_issue_extensions

Revision ID: e0ebcd77f922
Revises: 6eef61199a95
Create Date: 2021-09-09 03:05:02.970802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ebcd77f922'
down_revision = '6eef61199a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_extensions',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_extensions')
    # ### end Alembic commands ###
