"""add_column_image_path_in_Release

Revision ID: e4354fd3c12d
Revises: a15480f4a42f
Create Date: 2022-03-15 09:45:44.474520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4354fd3c12d'
down_revision = 'a15480f4a42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('image_path', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'image_path')
    # ### end Alembic commands ###
