"""add column

Revision ID: e4f7a65eab4c
Revises: 457ca5aab118
Create Date: 2022-10-27 09:32:14.827231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f7a65eab4c'
down_revision = '457ca5aab118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pict', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pict', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'pict', type_='foreignkey')
    op.drop_column('pict', 'project_id')
    # ### end Alembic commands ###
