"""add activity

Revision ID: e6a2fc6c3c7d
Revises: 00b0402a8197
Create Date: 2020-12-24 14:06:06.281142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a2fc6c3c7d'
down_revision = '00b0402a8197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('CREATE_PROJECT', 'UPDATE_PROJECT', 'DELETE_PROJECT', 'ADD_MEMBER', 'REMOVE_MEMBER', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', name='actiontype'), nullable=False),
    sa.Column('action_parts', sa.String(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('act_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(('operator_id',), ['user.id'], ondelete='SET NULL', name='fkey_activity_operator_id'),
    sa.PrimaryKeyConstraint('id', name='pkey_activity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
