"""Add IssueTag Table by array

Revision ID: eed6fad2720d
Revises: 32e48e03cf01
Create Date: 2021-09-10 14:06:42.029675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eed6fad2720d'
down_revision = '32e48e03cf01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_tag',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_tag')
    # ### end Alembic commands ###
