"""add_close_column

Revision ID: f06c4c5159ec
Revises: 62bca5258607
Create Date: 2022-04-12 14:20:29.031463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06c4c5159ec'
down_revision = '62bca5258607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_message', sa.Column('close', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_message', 'close')
    # ### end Alembic commands ###
