"""add_column_uuid_in_table_project

Revision ID: f32d3c521de0
Revises: bf01087eb736
Create Date: 2022-04-01 10:21:13.206749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32d3c521de0'
down_revision = 'bf01087eb736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'uuid')
    # ### end Alembic commands ###
