"""add_table_sbom

Revision ID: f373f135b9d7
Revises: 5045d9a6076f
Create Date: 2022-08-09 09:55:43.418425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f373f135b9d7'
down_revision = '5045d9a6076f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sbom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('commit', sa.String(), nullable=True),
    sa.Column('scan_status', sa.String(), nullable=True),
    sa.Column('package_nums', sa.Integer(), nullable=True),
    sa.Column('scan_overview', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('logs', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sbom')
    # ### end Alembic commands ###
