"""add_app_header_3_cols

Revision ID: f4e18cc12da5
Revises: c6e491604237
Create Date: 2023-03-03 13:39:39.017714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f4e18cc12da5"
down_revision = "c6e491604237"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("application_header", sa.Column("total_pods", sa.Integer(), server_default="0", nullable=True))
    op.add_column("application_header", sa.Column("creator_id", sa.Integer(), server_default="1", nullable=True))
    op.add_column("application_header", sa.Column("modifier_id", sa.Integer(), server_default="1", nullable=True))
    op.create_foreign_key(None, "application_header", "user", ["creator_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "application_header", "user", ["modifier_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("application_header_creator_id_fkey", "application_header", type_="foreignkey")
    op.drop_constraint("application_header_modifier_id_fkey", "application_header", type_="foreignkey")
    op.drop_column("application_header", "modifier_id")
    op.drop_column("application_header", "creator_id")
    op.drop_column("application_header", "total_pods")
    # ### end Alembic commands ###
