"""project add field image_auto_del

Revision ID: f5530d41c436
Revises: 1902122bdbcd
Create Date: 2023-06-14 14:14:09.101373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5530d41c436'
down_revision = '1902122bdbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_auto_del', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'image_auto_del')
    # ### end Alembic commands ###
