"""create_project_rescoure_storage_level

Revision ID: f640cdf79826
Revises: febb1cc19879
Create Date: 2022-06-15 15:38:11.753512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f640cdf79826'
down_revision = 'febb1cc19879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_resource_storagelevel',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('gitlab', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_resource_storagelevel')
    # ### end Alembic commands ###
