"""add_new_action_type_RECREATE_PROJECT

Revision ID: f6dae8356b30
Revises: 32f13f742b1a
Create Date: 2022-03-09 16:05:22.285308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6dae8356b30'
down_revision = '32f13f742b1a'
branch_labels = None
depends_on = None


def upgrade():
    # with op.get_context().autocommit_block():
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'RECREATE_PROJECT'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
