"""move version to db

Revision ID: fa67fc942daf
Revises: e6a2fc6c3c7d
Create Date: 2020-12-29 14:40:34.282420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa67fc942daf'
down_revision = 'e6a2fc6c3c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nexus_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('deploy_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pkey_nexus_version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nexus_version')
    # ### end Alembic commands ###
