"""redmine issue add assigned_to_id

Revision ID: fc2e4916a772
Revises: cb12fec0bcac
Create Date: 2021-04-12 15:51:26.529582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2e4916a772'
down_revision = 'cb12fec0bcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redmine_issue', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redmine_issue', 'assigned_to_id')
    # ### end Alembic commands ###
