"""adjust_image_path_type_in_Release

Revision ID: fd4a15862536
Revises: c8cf0f79f185
Create Date: 2022-03-15 14:54:39.621282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd4a15862536'
down_revision = 'c8cf0f79f185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('image_paths', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('release', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('image_path', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('release', 'image_paths')
    # ### end Alembic commands ###
