"""add template_list_cache table

Revision ID: fe09c879214d
Revises: c706d9781fe8
Create Date: 2021-04-09 15:26:47.123502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe09c879214d'
down_revision = 'c706d9781fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_list_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_repo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.JSON(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'temp_repo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_list_cache')
    # ### end Alembic commands ###
