apiVersion: v1
kind: Service
metadata:
  name: flask-${CICD_GIT_BRANCH}-production-service
  labels: 
    app: flask-${CICD_GIT_BRANCH}-production
spec:
  type: NodePort
  selector:
    app: flask-${CICD_GIT_BRANCH}-production
  ports:
    - name: flask-${CICD_GIT_BRANCH}-production-port
      protocol: TCP
      port: 8080
