apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels: 
    app: react
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - name: webport
      protocol: TCP
      port: 80
