apiVersion: v1
kind: Service
metadata:
  name: flask-${CICD_GIT_BRANCH}-service
  labels: 
    app: flask-${CICD_GIT_BRANCH}
spec:
  type: NodePort
  selector:
    app: flask-${CICD_GIT_BRANCH}
  ports:
    - name: flask-${CICD_GIT_BRANCH}-port
      protocol: TCP
      port: 8080
